export const DATE_TIME_PICKER = 'dateTimePicker'
export const DATE_PICKER = 'datePicker'
export const DROP_DOWN_LIST = 'dropdownList'
export const INPUT = 'input'
export const DESCRIPTION = 'description'
export const HIDDEN = 'hidden'
export const CHIPS = 'chips'
export const BUTTON = 'button'
export const NUMBER = 'number'
export const TEXT_AREA = 'textArea'
export const BLANK_FIELD = 'blankField'
export const HEADER_FIELD = 'headerField'

// this type is a special case
export const ORDER_VIA_TYPE = 'orderViaType'
export const STATUS_REASON = 'statusReason'
