export const DATE_TIME_PICKER = 'dateTimePicker'
export const DATE_PICKER = 'datePicker'
export const DROP_DOWN_LIST = 'dropdownList'
export const INPUT = 'input'
export const DESCRIPTION = 'description'
export const HIDDEN = 'hidden'
export const CHIPS = 'chips'
