cache:
  paths:
    - node_modules/

stages:
  - init
  - staging
  - deploy

init:
  stage: init
  image: node:15
  script: npm install

build-dev:
  stage: staging
  image: node:15
  only:
    - develop
  script:
    - npm run build
    - mv build dist
  artifacts:
    paths:
      - dist/build
    expire_in: 1 hour
    name: vitos-grill-app-artifact
    when: on_success
