stages:
  - staging
  - deploy

image: node:15

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - npm install --cache .npm --prefer-offline

build-dev:
  stage: staging
  script:
    - .echo success
  only:
    - develop
