stages:
  - staging
  - deploy

build-dev:
  stage: staging
  image: node:15
  script:
    - npm install
    - ./node_modules/.bin/env-cmd -f $env_development npm run build
  only:
    - develop

deploy:
