stages:
  - staging
  - production

cache:
  paths: node_modules/

build-dev:
  stage: staging
  image: node:15
  script:
    - npm install
    - env-cmd -f $env_development npm run build
  only:
    - develop
